---
- name: Initial setup of pis
  hosts: paramuno
  remote_user: root
  tasks: 
  - name: Update jar
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../../java-cep/target/beispiel-1.0-SNAPSHOT.jar"
      dest: /root/sm24/cep-node.jar
      owner: root
      group: root
  
  - name: Update python
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../../python/send_eventstream.py"
      dest: /root/sm24/
      owner: root
      group: root
